name = "sackar-atlas"
compatibility_date = "2026-04-15"
compatibility_flags = ["nodejs_compat"]
main = "./site/dist/server/entry.mjs"
no_bundle = true

[assets]
directory = "./site/dist/client"
binding = "ASSETS"
