#!/usr/bin/env python3
"""
extract-editorial-decisions.py — Scan source MD files for editorial decision comments
and generate EDITORIAL-DECISIONS.md.

Looks for HTML comments of the form:
    <!-- ed-format: ... -->
    <!-- ed-correct: ... -->
    <!-- ed-omit: ... -->
    <!-- ed-struct: ... -->
    <!-- ed-note: ... -->
    <!-- ed-uncertain: ... -->

Output is written to stdout. Redirect to sources/EDITORIAL-DECISIONS.md:
    python3 scripts/extract-editorial-decisions.py sources/ > sources/EDITORIAL-DECISIONS.md

Usage:
    python3 scripts/extract-editorial-decisions.py <directory> [--verbose]

Options:
    --verbose    Also print a summary to stderr
"""

import re
import sys
import os
import argparse
from datetime import date
from pathlib import Path


# Matches: <!-- ed-TYPE: content -->
# Also handles multi-line: <!-- ed-TYPE:\n  content\n-->
ED_RE = re.compile(
    r'<!--\s*(ed-(?:format|correct|omit|struct|note|uncertain))\s*:\s*(.*?)\s*-->',
    re.DOTALL
)

TYPE_LABELS = {
    'ed-format':    'Format',
    'ed-correct':   'Correction',
    'ed-omit':      'Omission',
    'ed-struct':    'Structure',
    'ed-note':      'Note',
    'ed-uncertain': 'Uncertain',
}


def scan_file(path):
    """Return list of (type, description) tuples for all ed-decisions in a file."""
    try:
        text = path.read_text(encoding='utf-8')
    except Exception as e:
        print(f'Warning: could not read {path}: {e}', file=sys.stderr)
        return []

    decisions = []
    for m in ED_RE.finditer(text):
        ed_type = m.group(1).strip()
        description = ' '.join(m.group(2).split())  # normalise whitespace
        decisions.append((ed_type, description))
    return decisions


def scan_directory(directory):
    """Walk directory, return dict of {relative_path: [(type, description)]}."""
    results = {}
    base = Path(directory)
    for md_file in sorted(base.rglob('*.md')):
        # Skip the register itself
        if md_file.name == 'EDITORIAL-DECISIONS.md':
            continue
        decisions = scan_file(md_file)
        if decisions:
            rel = str(md_file.relative_to(base))
            results[rel] = decisions
    return results


def render(results, directory):
    today = date.today().isoformat()
    total = sum(len(v) for v in results.values())

    lines = []
    lines.append('# Sackar Atlas — Editorial Decisions Register\n')
    lines.append('Auto-generated by `scripts/extract-editorial-decisions.py`.  ')
    lines.append('**Do not edit manually** — run the script to regenerate.\n')
    lines.append('```bash')
    lines.append('python3 scripts/extract-editorial-decisions.py sources/ > sources/EDITORIAL-DECISIONS.md')
    lines.append('```\n')
    lines.append('---\n')

    if not results:
        lines.append('## Register\n')
        lines.append('*No editorial decisions recorded yet. Annotate source files with '
                     '`<!-- ed-[type]: ... -->` comments, then run the script to populate this register.*\n')
    else:
        lines.append(f'## Register ({total} decision{"s" if total != 1 else ""} '
                     f'across {len(results)} file{"s" if len(results) != 1 else ""})\n')

        for rel_path, decisions in results.items():
            lines.append(f'### `{rel_path}`\n')
            lines.append('| Type | Description |')
            lines.append('|------|-------------|')
            for ed_type, description in decisions:
                label = TYPE_LABELS.get(ed_type, ed_type)
                # Escape pipes in description for table
                desc_escaped = description.replace('|', '\\|')
                lines.append(f'| {label} | {desc_escaped} |')
            lines.append('')

    lines.append('---\n')
    lines.append(f'*Last generated: {today}*\n')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate EDITORIAL-DECISIONS.md from inline ed-comments in source files.'
    )
    parser.add_argument('directory', help='Directory to scan (e.g. sources/)')
    parser.add_argument('--verbose', action='store_true', help='Print summary to stderr')
    args = parser.parse_args()

    if not os.path.isdir(args.directory):
        print(f'Error: {args.directory} is not a directory', file=sys.stderr)
        sys.exit(1)

    results = scan_directory(args.directory)

    if args.verbose:
        total = sum(len(v) for v in results.values())
        print(f'Found {total} editorial decision(s) across {len(results)} file(s)', file=sys.stderr)
        for path, decisions in results.items():
            print(f'  {path}: {len(decisions)} decision(s)', file=sys.stderr)

    print(render(results, args.directory))


if __name__ == '__main__':
    main()
